-- Luxury-Oriented Scenic Tours (LOST) Relational Schema

CREATE TABLE GUIDES (
    EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(255),
    EMP_ADDR VARCHAR(255),
    EMP_HIRE_DATE DATE
);

CREATE TABLE QUALIFICATION_LIST (
    ID INT PRIMARY KEY,
    EMP_ID INT,
    TOUR_ID INT,
    FOREIGN KEY (EMP_ID) REFERENCES GUIDES(EMP_ID),
    FOREIGN KEY (TOUR_ID) REFERENCES TOURS(TOUR_ID)
);

CREATE TABLE TOURS (
    TOUR_ID INT PRIMARY KEY,
    TOUR_NAME VARCHAR(255),
    TOUR_LEN INT,  
    TOUR_FEE DECIMAL(10,2)
);

CREATE TABLE TOUR_LOC_LIST (
    ID INT PRIMARY KEY,
    TOUR_ID INT,
    LOC_ID INT,
    FOREIGN KEY (TOUR_ID) REFERENCES TOURS(TOUR_ID),
    FOREIGN KEY (LOC_ID) REFERENCES LOCATIONS(LOC_ID)
);

CREATE TABLE LOCATIONS (
    LOC_ID INT PRIMARY KEY,
    LOC_NAME VARCHAR(255),
    LOC_TYPE VARCHAR(100),
    LOC_DES TEXT
);

CREATE TABLE OUTINGS (
    OUT_ID INT PRIMARY KEY,
    TOUR_ID INT,
    GUIDE_ID INT,
    DATE DATE,
    FOREIGN KEY (TOUR_ID) REFERENCES TOURS(TOUR_ID),
    FOREIGN KEY (GUIDE_ID) REFERENCES GUIDES(EMP_ID)
);

CREATE TABLE CLIENTS (
    CLIENT_ID INT PRIMARY KEY,
    CLIENT_NAME VARCHAR(255),
    CLIENT_TELE VARCHAR(20)
);

CREATE TABLE OUTING_CLIENTS (
    ID INT PRIMARY KEY,
    OUT_ID INT,
    CLIENT_ID INT,
    FOREIGN KEY (OUT_ID) REFERENCES OUTINGS(OUT_ID),
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID)
);
