-- United Helpers Relational Schema

CREATE TABLE VOLUNTEERS (
    VOL_ID INT PRIMARY KEY,
    VOL_NAME VARCHAR(255),
    VOL_ADDR VARCHAR(255),
    VOL_TELE VARCHAR(20)
);

CREATE TABLE TASKS (
    TASK_CODE INT PRIMARY KEY,
    TASK_DES VARCHAR(255),
    TASK_TYPE VARCHAR(100),
    TASK_STAT VARCHAR(50),
    PACK_LIST_ID INT,
    FOREIGN KEY (PACK_LIST_ID) REFERENCES PACK_LIST(PACK_LIST_ID)
);

CREATE TABLE PACK_LIST (
    PACK_LIST_ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    DES VARCHAR(255)
);

CREATE TABLE TASK_ASSIGN (
    ID INT PRIMARY KEY,
    VOL_ID INT,
    TASK_CODE INT,
    START_TIME DATETIME,
    END_TIME DATETIME,
    FOREIGN KEY (VOL_ID) REFERENCES VOLUNTEERS(VOL_ID),
    FOREIGN KEY (TASK_CODE) REFERENCES TASKS(TASK_CODE)
);

CREATE TABLE PACKAGES (
    PACKAGE_ID INT PRIMARY KEY,
    DATE_CREATED DATE,
    TOT_WEIGHT DECIMAL(10,2),
    TASK_CODE INT,
    FOREIGN KEY (TASK_CODE) REFERENCES TASKS(TASK_CODE)
);

CREATE TABLE ITEMS (
    ITEM_ID INT PRIMARY KEY,
    DES VARCHAR(255),
    VAL DECIMAL(10,2),
    QTY_ON_HAND INT
);

CREATE TABLE PKG_ITEMS (
    ID INT PRIMARY KEY,
    PACKAGE_ID INT,
    ITEM_ID INT,
    QTY INT,
    FOREIGN KEY (PACKAGE_ID) REFERENCES PACKAGES(PACKAGE_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ITEM_ID)
);
